# Generated by Django 5.2.2 on 2025-06-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OccurenceCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField(auto_now=True)),
                ("number", models.IntegerField(default=0)),
                ("value", models.IntegerField(default=0)),
                ("occurences", models.IntegerField(default=0)),
                ("last_datetime", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
